version: '3.8'

services:
  gemini-agent:
    build: . # <-- 改回这一行，让它在云端自己建造
    container_name: gemini-agent-container
    ports:
      - "5000:5000"
    volumes:
      - ./project_files:/workspace
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
